### ISSUE TITLE
Add links to repositories using imgui-rs to readme file

### ISSUE THREAD

**Issue by jaroslaw-weber** [imgui-rs/imgui-rs#100]
I am proposing that we add external links to other repositories using this library inside the readme file. There are only two examples inside. It is easier to add link to other repository than copy and maintain examples.

https://github.com/jaroslaw-weber/imgui_calculator

I created a simple calculator using this library. I think it may be good example (something between hello world and more advanced example.

**Comment by dbr** [comment]
Closing old ticket

I'm not in favour of a list of projects using imgui-rs, just because it requires constant maintenance to keep up-to-date, and is probably better solved by search (like the reverse dependenices section on crates.io, or searching github for imgui with lanague:rust)

The "easier to copy-paste" part is something that would be helped by #664
