### ISSUE TITLE
Pure imgui crate examples

### ISSUE THREAD

**Issue by nico-abram** [imgui-rs/imgui-rs#229]
I could only find examples using all/most of the crates in the repo. It'd be nice to have examples of how to use just imgui (I was looking to maybe use it with https://github.com/Lokathor/beryllium )

**Comment by Gekkio** [comment]
To run the examples, you always need renderer and platform support, so pure imgui crate examples would not be very useful since they would not be runnable.

**Comment by clouds56** [comment]
I feel frustrated when setting up imgui. I know the most case is integrate imgui in some game, while could I run it as a gui framework?
If imgui could include basic glue code like [support](https://github.com/Gekkio/imgui-rs/blob/master/imgui-examples/examples/support) mod in example that would be great. So that we could start a new project just add dependencies and run the code in REAMDE:

```toml
[dependencies]
imgui = "0.4.0"
imgui_support = "0.4.0" # cross-platform config for imgui
# or imgui = { version = "0.4.0", features = [ "support" ] }
```

```rust
use imgui::*;

fn main() {
    // provide glue code in imgui
    // so that we could use it like a gui library
    let system = imgui_support::Builder::new().init();
    system.main_loop(move |_, ui| {
        Window::new(im_str!("Hello world"))
            .size([300.0, 110.0], Condition::FirstUseEver)
            .build(ui, || {
                ui.text(im_str!("Hello world!"));
                ui.text(im_str!("こんにちは世界！"));
                ui.text(im_str!("This...is...imgui-rs!"));
                ui.separator();
                let mouse_pos = ui.io().mouse_pos;
                ui.text(format!(
                    "Mouse Position: ({:.1},{:.1})",
                    mouse_pos[0], mouse_pos[1]
                ));
            });
    });
}
```

I think this could make imgui more attractive for people to try.

**Comment by nico-abram** [comment]
That support layer in examples can be quite restrictive iirc, you probably can start off from it but eventually will run into something you can't do without changing it (And if it's in your own code you can do that easily). I'm not sure using imgui as a general GUI toolkit is a super good idea in the general case, but there's plenty written about that on the internet already.

**Comment by sztomi** [comment]
I agree that it would be nice to have a minimalistic support library. All examples use this support module and it's a non-trivial amount of code. If it's too restrictive, maybe with lesser functionality included.

**Comment by dbr** [comment]
> That support layer in examples can be quite restrictive iirc, you probably can start off from it but eventually will run into something you can't do without changing it

I found the same when first using the `imgui-rs` - having not used much imgui/winit/glium, the extra layer of the `support` module made it harder to work out how/if I could do even simple things like change the window title (because in the context of the example code, you couldn't get mutable access to the window). When I eventually unwrapped all the support module code into my application, it became much clearer

This aspect will be helped a lot by #495 - it has a `01_basic.rs` example which is completely self contained.

**Comment by jmaargh** [comment]
When writing the new glow renderer, which has now been merged to master, I made sure to include an [entirely self-contained minimal example](https://github.com/imgui-rs/imgui-rs/blob/master/imgui-glow-renderer/examples/01_basic.rs) because I like to know how things are put together more-or-less end to end. I hope this helps

**Comment by dbr** [comment]
Closing; the glow render example linked above is about the most minimal amount of code possible to use imgui-rs in a practical manner :partying_face:
