### ISSUE TITLE
imgui-wgpu-renderer?

### ISSUE THREAD

**Issue by yanchith** [imgui-rs/imgui-rs#243]
Would you be interested in having an `imgui-wgpu-renderer`, once `wgpu` slows down a bit more (perhaps with 0.3)?

There already is https://github.com/unconed/imgui-wgpu-rs, but that seems stale at the moment of writing this.

We have one working, tracking `imgui-rs` 0.1, and current `wgpu` master and are more than willing to contribute. It isn't published currently, but I can share a gist.

EDIT: https://gist.github.com/yanchith/70871d783789853395f3896d254cf8c4

It uses a translate/scale pair instead of an ortho matrix, and currently has a workaround for updating the uniform buffer, but otherwise seems to work. It also compiles the shaders in runtime, but that's trivial to change.

**Comment by Yatekii** [comment]
I have a made a fork here: https://github.com/Yatekii/imgui-wgpu-rs which works with upstream wgpu. I will maintain it, but not PR upstream as the original author seems inactive.

I would also publish to crates.io once the dependencies have proper releases (I made some fixes to imgui-rs (outdated winit) and it is using the 0.2 upstream).

The only thing not working properly yet is HiDpi. I didn't have the time to investigate that yet.

The code also needs a lot of cleanup (code from the original author).

Font loading needs some work too.

**Comment by brendanzab** [comment]
Is it possible to get this into this repository, alongside the glium and gfx renders? It seems like the gfx renderer might need to be deprecated, given it is for the pre-ll version of gfx. 🤔

**Comment by Yatekii** [comment]
I thought about that, but then I have no control over release cycles etc. and since wgpu is fast going I'd prefer to be able to release quick too :)

**Comment by dbr** [comment]
Closing, gfx render is now deprecated, and as mentioned wgpu is quite fast moving (even still) so wouldn't necessarily line up well with imgui-rs release cycle. Having it in this crate wouldn't give it any special access to imgui-rs

This might be work revisiting later if glium becomes "deprecated" (rather than it's current "not actively developed" state), as I think it's good to have two "officially maintained" renderers in the repo, and wgpu is probably the best candidate - but, definitely something for future
