### ISSUE TITLE
hello_world example creates a larger window on wayland (sway)

### ISSUE THREAD

**Issue by knightshrub** [imgui-rs/imgui-rs#246]
I am running the hello_world example on sway (wayland) and the window created is much larger than the actual imgui ui. 
When going into floating mode there still are these large white areas around the actual UI window.

Is this a bug in imgui-rs or does it have to do with glutin (or maybe even sway)?

![helloworld](https://user-images.githubusercontent.com/743917/62138154-b15e3f00-b2d6-11e9-8551-60c6eee901ab.png)

**Comment by Gekkio** [comment]
That looks completely normal to me, because the native window size is not the same as imgui window size. The native window is basically just a "canvas" where one of the imgui renderers draws and there's no direct connection between the "canvas size" and the size of anything drawn inside it.

It's also worth pointing out that the last time I tried running some imgui-rs examples on wayland, it was a completely buggy mess. So, you might be seeing also some extra issues because wayland doesn't really work well yet. I suspect the main problem is that wayland support in winit isn't very mature yet...

**Comment by dbr** [comment]
Closing as per previous comment - looks like it's working as expected (imgui is intended to render into a single OS-level window, at least until the multi-viewport feature is complete e.g #619 )

There are definitely some weird bugs with winit+wayland (e.g in sway 1.6 the window content would be [rendered with an incorrect offset](https://github.com/swaywm/sway/commit/4e6f51525308a8883bf998a360a192edc0822cdd)) - and generally still a fairly fast-moving project
