### ISSUE TITLE
Docking?

### ISSUE THREAD

**Issue by cheako** [imgui-rs/imgui-rs#249]
I've tested Docking and it doesn't seem to work.  I know this is a new feature to imgui so am patiently looking for assistance or time-fame.

**Comment by Gekkio** [comment]
In the upstream C++ library, docking is an experimental extra feature maintained in a separate branch, and imgui-rs provides bindings only to the main releases of dear imgui. Once docking gets merged in upstream, it'll be supported in imgui-rs as well.

**Comment by luke-titley** [comment]
Hey, so I really want this feature, so I'm happy to do the work for this. Am looking into it now.

**Comment by rasky** [comment]
Notice that a port of the docking branch already exists: https://github.com/Gekkio/imgui-rs/pull/285

It works (I'm using it). It's using the docking branch from January 2020, I can update it if somebody wants to use a newer one.

**Comment by luke-titley** [comment]
@rasky This is awesome. Looks like you've done what I just spent today doing. Updated to the docking_inter branch on cimgui repo. Can you update now ?

**Comment by RoyJacobs** [comment]
It would be great if the `docking` branch stuff could be at least on the same API version as the regular imgui bindings (compatible with 1.77 at time of writing I guess). That would make it very easy to switch.

I'm assuming this work is just for the docking flags and not for the multi-window support?

**Comment by luke-titley** [comment]
@Gekkio, what do you think about making a long lived 'docking' branch in this repo?, to parallel the one in the upstream c++ repo? It would bring rust users up to speed with what c++ developers have had for a year or more?

**Comment by luke-titley** [comment]
@rasky hey. I copied your io.rs changes into my fork. So please don't rush to update, but when you do. Let me know, I'll sync to your work.

**Comment by luke-titley** [comment]
Hey @Gekkio, have you got any time to talk about this? It would be great to get this work into this repo?

**Comment by Gekkio** [comment]
Sorry, but as I've said before, experimental features will not be supported in imgui-rs because of the maintenance overhead.
Upstream doesn't consider docking good enough to be merged to master -> I don't consider docking worth the maintenance cost.

People can create or use forks that add support to these kind of things, but my recommendation is to direct all effort to helping upstream stabilize this feature, although I don't know what is needed to make it happen...testing? API feedback? actual programming work? In any case, docking is not in master, and there's no plans to support the various feature branches of Dear ImGui in imgui-rs.

**Comment by luke-titley** [comment]
Hey,
Sorry I seemed to have posted a reply at the same time as you under issue #292 talking about the same thing.
I am disappointed, but I understand. Would you be opposed to another crate being created that contains the docking work ? imgui-docking-rs, something like this? For people who want access to the beta docking work, without having to clone it themselves?

**Comment by luke-titley** [comment]
Hey so following on from @Gekkio's request to have a fork repo for the docking work I've put an up to date repo online here:
https://github.com/luke-titley/imgui-docking-rs.

I'll try to keep this up to date so that there is a single place to go for a repo that has all the latest and greatest from imgui-rs but also docking.

Although this risks fragmenting development a little, there is no need to fragment the discussion about what the dockbuilder api should look like for imgui-rs, so I think it's still worth discussing on this issue and not an issue on that repo. The api for the DockBuilder in dearimgui has been stable for over a year now, so i'm hoping it won't change too much before it is merged to master.

If anyone has already done this work already, please say so and I'll just copy that, I need this feature now and I'm just trying to make sure I don't have to re-write the api when there is an official imgui-rs api.

Here's what I have now.

So you build your UI like normal.
```
imgui::Window::new(im_str!("Viewport")).build(&ui, || {/*..*/});
imgui::Window::new(im_str!("NodeGraph")).build(&ui, || {/*..*/});
imgui::Window::new(im_str!("Properties")).build(&ui, || {/*..*/});
imgui::Window::new(im_str!("Outliner")).build(&ui, || {/*..*/});
```

Then you build the docking layout.
```
imgui::Dock::new().build(|root| {
    root.size([500_f32, 500_f32]).position([0_f32, 0_f32]).split(
        imgui::Direction::Left,
        0.7_f32,
        |left| {
            left.dock_window(im_str!("Viewport"));
            left.dock_window(im_str!("NodeGraph"));
        },
        |right| {
            right.dock_window(im_str!("Properties"));
            right.dock_window(im_str!("Outliner"));
        },
    )
});
```

It's basically just copying the builder mechanism imgui-rs already has.

**Comment by RoyJacobs** [comment]
@luke-titley Great work! If it's not too much trouble, could you throw that sample code into an example.rs? I'm trying to add docking to my app using your branch and the dock windows aren't responding correctly so I was wondering if I could repro it using a bare bones example.

**Comment by luke-titley** [comment]
ok. Make sure you're using the docking branch. That's the default on github, but you might not have switched to it after clone. I'm gonna keep master identical to the master branch on this repo.

**Comment by luke-titley** [comment]
So I've uploaded an example.
Should look like this.

<img width="511" alt="Screenshot 2020-09-21 at 21 07 08" src="https://user-images.githubusercontent.com/55767239/93810125-7e031000-fc4e-11ea-8cf4-6952c4d54b5f.png">

```rust
imgui::Dock::new().build(|root| {
                root.size([512_f32, 512_f32])
                    .position([0_f32, 0_f32])
                    .split(
                        imgui::Direction::Left,
                        0.7_f32,
                        |left| {
                            left.dock_window(im_str!("Hello"));
                        },
                        |right| {
                               right.split(imgui::Direction::Up, 0.5_f32,
                                |top| {
                                    top.dock_window(im_str!("Docking"));
                                },
                                |bottom| {
                                    bottom.dock_window(im_str!("Awesome"));
                                }
                               );
                        },
                    )
            });
        }
```

**Comment by RoyJacobs** [comment]
@luke-titley Thanks! It wasn't clear to me that the dock should only be created once, since that wasn't part of your example in the readme. Changing that in my code makes it work perfectly.

**Comment by qthree** [comment]
![imgui_wgpu_viewports](https://user-images.githubusercontent.com/9898555/94697327-45f08100-0362-11eb-9388-5cb10002f789.gif)
Done some experimenting with imgui-wgpu and viewports. Still a long way to make it stable and encapsulate in a safe abstraction, but it works.

**Comment by luke-titley** [comment]
Have rebased docking repo on top 0.5.0.
Branch 'release/docking/0.5.0'

**Comment by Boscop** [comment]
@luke-titley Btw, is [this draggable edge](https://github.com/Gekkio/imgui-rs/issues/292#issuecomment-691682877) between ChildWindows only possible in the docking branch?
Or is it also possible with the current imgui-rs master? I have a real need for draggable edges in my UI..

**Comment by luke-titley** [comment]
@Boscop
hey. Sorry for the slow reply. I think it's only available on the docking branch. Without the docking, windows float around independently.

**Comment by luke-titley** [comment]
@thomcc 
Since imgui-rs is under a new direction. Is it possible to re-start this discussion ? At the moment I have a fork of imgui-rs which just has the docking feature in. Is it possible to bring that in to at least this repo ? With either the same api or an equivalent/better one?

**Comment by sanbox-irl** [comment]
@luke-titley that would be great. I think we'd ideally solve https://github.com/imgui-rs/imgui-rs/issues/435 first. There's another branch, a string_view branch, which theoretically could obviate the need for the `im_str` macro. That'd be a pretty great improvement too. If we could more easily generate these bindings, then we'd be in a better place for implementing more branches more easily.

**Comment by luke-titley** [comment]
agreed, it's a pain to update. That's why my fork is still on 0.5. I takes me half an hour to remember/update to the latest.

**Comment by NoxWings** [comment]
In case anyone wants to check I've got a branch on 1.81 with docking support enabled. I am currently using the unsafe API if I ever need to do anything related to docking but it works. Don't use them directly as I'll probably change them for my needs by feel free take a look.

This is what I'm currently using on my cargo.toml
```toml
imgui = { git = "https://github.com/NoxWings/imgui-rs.git", tag = "1.81dock" }
imgui-sdl2 = { git = "https://github.com/NoxWings/rust-imgui-sdl2.git" }
imgui-opengl-renderer = { git = "https://github.com/NoxWings/rust-imgui-opengl-renderer.git" }
```

This is pretty much the only thing you need to enable it
```rust
let mut context = Context::create();
context.io_mut().config_flags |= ConfigFlags::DOCKING_ENABLE;
```

**Comment by TimonPost** [comment]
Would be nice if this could be integrated into the official library

**Comment by eliaperantoni** [comment]
@thomcc Sorry to bother but can I ask what the plans are for docking support in this crate?

I know it's experimental in the upstream library but I think the value it provides is so incredibly high that an implementation is well worth it in my opinion. C++ devs have been enjoying this feature since 2018.

Maybe even provide unsafe bindings, for the time being, so we can dip our toes without resorting to third party forks.

**Comment by thomcc** [comment]
I'm no longer the lead maintainer (@sanbox-irl has taken over), but there's some discussion over https://github.com/imgui-rs/imgui-rs/issues/531.

It's hard to provide both, and doesn't scale well unfortunately... but it's still a goal.

**Comment by eliaperantoni** [comment]
Oh sorry I should've known that. Reading the issue you mentioned I now understand a little bit more the technical challenges that make supporting `docking` hard. Thank you!

**Comment by dbr** [comment]
Done in https://github.com/imgui-rs/imgui-rs/pull/557 which will be part of imgui-rs 0.9
