### ISSUE TITLE
igBeginTabBar() and igBeginTabItem()

### ISSUE THREAD

**Issue by JoeHsiao** [imgui-rs/imgui-rs#277]
```
use imgui::*;
mod support;

fn main() {
    let system = support::init(file!());
    system.main_loop(|_, ui| {
        Window::new(im_str!("Hello world"))
            .size([300.0, 200.0], Condition::FirstUseEver)
            .build(ui, || {
                let mut open: bool = true;
                unsafe { sys::igBeginTabBar("bar".as_bytes().as_ptr() as *const i8, 0 as ::std::os::raw::c_int) };
                unsafe { sys::igBeginTabItem("tab".as_bytes().as_ptr() as *const i8, &mut open, 0 as ::std::os::raw::c_int) };
                unsafe { sys::igEndTabItem() };
                unsafe { sys::igEndTabBar() };
            });
    });
}
```
![imgui-tab](https://user-images.githubusercontent.com/4561007/68032632-77655600-fc94-11e9-98e0-9c36898b40ee.png)

*igBeginTabBar()* and *igBeginTabItem* kind of gave me strange results:
1.  It shows an "x" icon at the end of tab when mouse hovers over. If I click that, the program would crash with the message
```Assertion failed: *p_backup == current && "PushID/PopID or TreeNode/TreePop Mismatch!", file third-party/cimgui/imgui/imgui.cpp, line 4781```
2. The text on the tab includes the window's title "Hello world". 

Am I using the API wrong?

**Comment by TheDestroyer19** [comment]
Starting with 2. Dear Imgui uses null terminated strings. In other words, you forgot to tell Dear Imgui when your ids end. So we could fix that by appending a null onto the end of your strings slices, which looks like this:
```
unsafe { sys::igBeginTabBar("bar\0".as_bytes().as_ptr() as *const i8, 0 as ::std::os::raw::c_int) };
unsafe { sys::igBeginTabItem("tab\0".as_bytes().as_ptr() as *const i8, &mut open, 0 as ::std::os::raw::c_int) };
unsafe { sys::igEndTabItem() };
unsafe { sys::igEndTabBar() };
```
A solution that fits better with the safe API would be to use the `im_str!()` macro and `ImStr::to_ptr()' (see [API design: string arguments (static) #7](https://github.com/Gekkio/imgui-rs/issues/7)). That would look something like this:
```
unsafe { sys::igBeginTabBar(im_str!("bar").as_ptr(), 0 as ::std::os::raw::c_int) };
unsafe { sys::igBeginTabItem(im_str!("tab").as_ptr(), &mut open, 0 as ::std::os::raw::c_int) };
unsafe { sys::igEndTabItem() };
unsafe { sys::igEndTabBar() };
```
With either of these changes running your program should result in something like this (without the blue square in the background):
![Screenshot from 2019-11-15 12-50-43](https://user-images.githubusercontent.com/17345449/68971436-c0460000-07a6-11ea-9da4-d9083dfd850d.png)
------
As for the program crashing when a user clocks on the `X` we need to go to the C library's documentation which is mostly in [Dear Imgui's imgui.h file](https://github.com/ocornut/imgui/blob/master/imgui.h). At line 596 it states `only call EndTabItem() if BeginTabItem() returns true!` and similarly for `EndTabBar()`
Reworking the code to respect that constraint looks something like this:
```
unsafe {
  if sys::igBeginTabBar(im_str!("bar").as_ptr(), 0 as ::std::os::raw::c_int) {
    if sys::igBeginTabItem(im_str!("tab").as_ptr(), &mut open, 0 as ::std::os::raw::c_int) {
      sys::igEndTabItem();
    }
    sys::igEndTabBar();
  }
}
```
This code no longer crashes when pressing the `X`, but the tab now flickers, because Dear ImGui thinks that the tab was closed and then immediately reopened. We can remove the `X` by passing `null_mut()` to `igBeginTabItem()` instead of a reference to `open`. This would make your final code look like:
```
use imgui::*;
mod support;

fn main() {
    let system = support::init(file!());
    system.main_loop(|_, ui| {
        Window::new(im_str!("Hello world"))
            .size([300.0, 200.0], Condition::FirstUseEver)
            .build(ui, || {
                unsafe {
                    if sys::igBeginTabBar(im_str!("bar").as_ptr(), 0 as ::std::os::raw::c_int) {
                        if sys::igBeginTabItem(im_str!("tab").as_ptr(), null_mut(), 0 as ::std::os::raw::c_int) {
                            sys::igEndTabItem();
                        }
                        sys::igEndTabBar();
                    }
                }
            });
    });
}
```
I hope this helps with your project!

**Comment by JoeHsiao** [comment]
Works like a charm.
Thank you for the clear explanation.

**Comment by dbr** [comment]
Believe this has since been exposed in the main `imgui` crate as `Ui::tab_bar` and `Ui::tab_item` etc - so should now be much simpler to use compared to the raw `sys` crate
