### ISSUE TITLE
gamepad support

### ISSUE THREAD

**Issue by ascii78** [imgui-rs/imgui-rs#361]
Hi,

I'm trying to access an xbox gamepad using imgui but can't seem to get any values  (examples/helloworld.rs):  

```rust
                let mouse_pos = ui.io().mouse_pos;
                let mouse_down = ui.io().mouse_down[0];
                ui.text(format!(
                    "Mouse Position: ({} {:.1},{:.1})",
                    mouse_down, mouse_pos[0], mouse_pos[1]
                ));
   
                for i in 0..ui.io().nav_inputs.len() {
                // reset to 0, only print if there's anything there
                    if ui.io().nav_inputs[i] != 0.0 {
                        println!("nav_input{}: {}", i, ui.io().nav_inputs[i]);
                    }
                }
```
From what I can read in Io.rs is that i may need to set configflags/backendflags (HAS_GAMEPAD seems on) but I'm not sure how to do it. I've also used other crates (gilrs/sfml)  but that is a bit messy with different event loops, they do seem to read the gamepad just fine though. glutin/winit also works but moves the event processing to support/mod.rs.

**Comment by dbr** [comment]
Closing old issue

I think you would basically just have to set `HAS_GAMEPAD` and handle the relevant events from `winit` or whatever you are using in your main event loop, basically replacing this fall-through branch of the `match`
https://github.com/imgui-rs/imgui-rs/blob/v0.9.0/imgui-glow-renderer/examples/glow_01_basic.rs#L69
..and do something similar to this code:
https://github.com/imgui-rs/imgui-rs/blob/6d6cda275cbe9330fca9352f46b234f6d8616702/imgui-winit-support/src/lib.rs#L327
only for the events produced by the gamepad (instead of `DeviceEvent::Key` and `WindowEvent::CursorMoved` etc etc)
