### ISSUE TITLE
Determine policy around MSRV and new MSRV

### ISSUE THREAD

**Issue by thomcc** [imgui-rs/imgui-rs#402]
I suspect I'll be bumping the MSRV to at least 1.46 to take advantage of const fn, but more broadly, I'd like a policy here.

More broadly, I'd like to find a more tenable strategy for MSRV than either:

- waiting for our deps to force us to bump it.
- forcing latest stable.

My inclination here is to adopt a policy of `stable - N` (e.g. `stable - 1` would mean we support stable and the previous release). I'm thinking `N` is between 1 and 3. (It seems like a good balance that's predictable, avoids the worst problems of "latest stable", while not forcing you to make the semver number useless).

The other option I'm fond of is to consider it a minor (but not major) bump, which is not really relevant here, but avoids the version becoming almost entirely meaningless.

**Comment by sanbox-irl** [comment]
I think the minor bump is the right call.

Most large projects will be using a fork, or a completely specified version, of this project anyway, so "surprising" someone with an update, when they aren't updated rustc, would surprise me.

I dislike keeping up with stable Rust since this forces significant amounts of updates just to keep to MSRV policy.

**Comment by thomcc** [comment]
The issue with it being a minor bump is that prior to 1.0 (which I'm not ready for) is that it's equivalent to no policy at all.

**Comment by sanbox-irl** [comment]
the underlying idea here is that you intend to move the repo to be MSRV on the new update of Rust which is expected to have min_const_generics, right?

**Comment by thomcc** [comment]
I meant the const fn changes of 1.46, but it's possible there's some array code that would benefit from min_const_generics.

**Comment by dbr** [comment]
For tools where they are likely to be packaged by distros, using a minimum version of "whatever is packaged in most distros" is a good approach to MSRV policy, however that probably isn't a major consideration for imgui-rs.

Otherwise I'd be happy with incrementing it "as needed" - e.g bumping the MSRV for a minor helper method which reduces 2 lines to 1 is probably not worthwhile, but for something like the const-generics, sure.

I don't have strong opinions on if bumping the MSRV being a major bump versus minor etc. The thing I *do* have strong opinions on is: bump the version intentionally, and note the change in the changelog

So on these lines, I've made a PR to test the current minimum version in CI:

https://github.com/imgui-rs/imgui-rs/pull/512

That way if a PR adds usage of something added after 1.48 it'll be easy to spot - and either the version can be bumped or the PR be altered

**Comment by sanbox-irl** [comment]
Okay -- as of commit 04af6ab69af61246a2d152a3e2755d02cdabb7a4, I've committed our MSRV to 1.54 (updating our CI to reflect this) and noted it in the readme. For only this release, I've added a feature gate around min-const-generics (which is used in the tables-api a bit, and I'd like to use in the string api too) and added it as a default feature. In 0.9.0, that'll be removed and all msrv jumps will have the minor break in them, but since this is the first intentional one, it felt fair to give a cushion.

I'm going to close this issue, but if anyone would like to debate or change this, feel free to comment and I'll reopen
