### ISSUE TITLE
add original imgui names as doc aliases to functions 

### ISSUE THREAD

**Issue by benmkw** [imgui-rs/imgui-rs#456]
same as https://github.com/4bb4/implot-rs/issues/11

https://blog.rust-lang.org/2020/11/19/Rust-1.48.html#adding-search-aliases

> An interesting use case for aliases is FFI wrapper crates, where each Rust function could be aliased to the C function it wraps. Existing users of the underlying C library would then be able to easily search the right Rust functions!

This is busy work but might help people to get startet/ find what they are looking for when porting cpp imgui code.

**Comment by sanbox-irl** [comment]
wow, great idea! this is however, non-trivial in practice, though welcome. Our big tasks this release are, hopefully, completing the drawlist wrapper, make our bindings to optional arguments simpler, nicer tokens for state on the stack, and removing im_str! from the codebase. So things are a bit busy right now.

If someone wants to help though, your contribution would be more than welcome (please comment and say "i'll take these modules", since this is probably a bigger task than a single person wants to do and we can divide the codebase up):

1. Functions on the `Ui` struct are highest priority. Those should be aliased to their underlying FFI call, which should be obvious in practice what it's referring to (most of them as just wrappers around their call). For example:
```rs
    pub fn separator(&self) {
        unsafe { sys::igSeparator() }
    }
```
should be bound like:
```rs
    #[doc(alias = "Seperator")]
    pub fn separator(&self) {
```

Note the capitalization -- ImGui functions are PascalCase. If our goal is that someone can search imgui functions in docs.rs and find the bindings, then we should follow that to make it useful.

As a minor note, depending on when this task is accomplished, there may be some wrapper functions which handle default arguments. If it's possible (I'm not sure) to have multiple functions have the *same* search alias, then all should have the same search alias. If now......leave a comment and we can handle it on a case by case basis. Probably the shortest version should be bound, since it's easy to walk up from the shortest to the longest version, while the functions will all parameters in them and no default arguments are not as obviously related to their overriden cousins. 

2. Builders:

So a huge category of this API is making builders to emulate extensive default arguments / immediate mode stack building. The Window struct is a great example of this. 

Binding the aliases to these functions could prove very tricky. Ideally, the builder functions which correspond to underlying usage should be flagged with their parent function, but that might even be more confusing. Take for example:

```rs
    #[inline]
    pub fn position(mut self, position: [f32; 2], condition: Condition) -> Self {
```
This is within the WindowBuilder api. It's a bit odd, but this *actually* corresponds to `SetNextWindowPos`, and you can see this all the way in the `begin` method:
```rs
        if self.pos_cond != Condition::Never {
            unsafe {
                sys::igSetNextWindowPos(
                    self.pos.into(),
                    self.pos_cond as i32,
                    self.pos_pivot.into(),
                )
            };
        }
```        
so in an ideal world, these builder functions would have the doc alias of what they defer doing as well. If that seems confusing in practice though, there's no reason we have to do everything.

3. The Etc functions:

Things like handling platforms, fonts, basically everything that isn't the core Ui API. These should be aliased as well but are the lowest priority -- our primary use case here is someone looking at the imgui_demo.cpp and trying to translate that into Rust, and so #1 and #2 should be a help there.

Thank you so much for submitting the idea, and if anyone has the time, and a few good podcasts, and wants to help out, it would be fantastic!

**Comment by toyboot4e** [comment]
I tried adding aliases to `src/*.rs` (except for `drag_drop.rs`): [doc_alias](https://github.com/toyboot4e/imgui-rs/commits/doc_alias) branch.
I can make alises for sub module items in later days (if no one does it).

Notes:

<details><summary>Mulitple functions with same aliases is possible (to: @sanbox-irl)</summary>
<img width="816" alt="same-aliases-from-diff-items" src="https://user-images.githubusercontent.com/47905926/109779424-48287580-7c49-11eb-872f-b17afee4c53a.png">
</details>

<details><summary>Some functions got multiple aliases so that they can be searched with category</summary>

```rust
    //             category               ImGUI function name
    #[doc(alias = "StyleColors", alias = "StlyeColorsClassic")]
    pub fn use_classic_colors(&mut self) -> &mut Self {
```
<img width="806" alt="style-colors" src="https://user-images.githubusercontent.com/47905926/109779847-b836fb80-7c49-11eb-9dda-5755ac171c25.png">
</details>

> Note: Alias `TestA` can be searched with `TestA` or `testa`, but can' be searched with `Test`.

I think I might have made errors, but maybe it's better than nothing :)

**Comment by sanbox-irl** [comment]
Awesome @toyboot4e !

**Comment by sanbox-irl** [comment]
There is now a PR for this <https://github.com/imgui-rs/imgui-rs/pull/458>

**Comment by sanbox-irl** [comment]
hey @toyboot4e i haven't checked our total coverage yet, but do you think I'm good to close this, or is there still extra work that needs to be done? I think glancing over, we have good enough coverage now, yeah?

**Comment by toyboot4e** [comment]
If we want completeness, `drag_drop.rs` (complex code) and `token.rs` (macros) are needed to be worked with.
But yes I think most functions are covered, which would be good enough :)

**Comment by sanbox-irl** [comment]
Ah, I wrote the drag_drop.rs implementation, so I can take a look and fix those aliases up. For now, I'll close the issue. Thanks again!
