### ISSUE TITLE
What is "support"?

### ISSUE THREAD

**Issue by chaoxi24** [imgui-rs/imgui-rs#466]
I noticed that all "imgui-examples" use it, and there is no description.
Sorry, I am new to rust, I rely heavily on "examples" to learn how to use imgui. I am very curious about what "support" is. If it is "must", I think "imgui::support" is more reasonable. If it is not necessary, I think I am very eager for an example without it. Or explain what it is.

**Comment by jmaargh** [comment]
Not a maintainer here, just some friendly advice.

`support` seems to be a helper module in the `examples` crate, code is here: https://github.com/imgui-rs/imgui-rs/tree/master/imgui-examples/examples/support

This isn't uncommon with libraries with lots of examples, they tend to factor out code common to many examples into a module each example calls into.

**Comment by dbr** [comment]
Also not a maintainer, but.. exactly as @jmaargh says, the `support` module helps avoid duplicating the main rendering loop code in every example. The `support` module refers to the `support/mod.rs` file inside the examples directory, and isn't something which can live in imgui-rs itself (since it uses the `imgui-glium-renderer` and `imgui-winit-platform` crates, and imgui itself has to work with any possible backends)

For example, in
https://github.com/imgui-rs/imgui-rs/blob/97d5dc8502d8213b909431d9926df39bec271e17/imgui-examples/examples/hello_world.rs
the line `let system = support::init(file!());` calls the init method here:
https://github.com/imgui-rs/imgui-rs/blob/97d5dc8502d8213b909431d9926df39bec271e17/imgui-examples/examples/support/mod.rs#L23

This `init` method does a bunch of stuff, mainly:

- It creates a window using winit, creates an OpenGL rendering context with glium, connects up things like the keyboard and mouse input
- Creates an `imgui::Context`, and calls `.frame()` producing the all-important `imgui::Ui` object. This gets passed into the `main_loop` closure method you see in all the examples
- Once the closure is done, it passes the imgui data to a renderer (in these examples, the `imgui-glium-renderer` crate in the imgui-rs repo)

Since imgui is designed to be usable in any rendering environment (e.g embedded in a game engine, or or an existing OpenGL engine, etc etC), the examples all focus on using imgui widgets etc, rather than how best to setup the rendering process.

So hopefully that explains what it does, and why it is necessary. However I do agree it would be nice if there was a "self contained" example showing how setup everything from scratch - which is possibly something which belongs in something like a "user guide" doc for the renderer backend

Note you can just copy `support` into your project and use it pretty much as-is (there is a font path which needs fixed, and maybe a few other minor tweaks). You can also just edit the examples to experiment. It's not the simplest, but given imgui's flexible nature it's a little unavoidable

**Comment by thomcc** [comment]
I am a maintainer, but couldn't have said it better than @dbr (thanks).

That said, I agree that it might be nice if we had one or two fully self-contained examples. I've thought for a while that maybe we over-rely on the `support` module in them, and it makes things harder to understand even in more complete engines.

OTOH I don't have concrete plans to address this, nor the time to figure some out.

**Comment by chaoxi24** [comment]
Thank you for your answers. I have no other questions.
