### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by eliaperantoni** [imgui-rs/imgui-rs#505]
**Describe the bug**
The whole ImGui UI appears zoomed-in. This happens on my laptop but not on my desktop (specs found at the end of the post).

**To Reproduce**
`cargo run --example hello_world`

**Expected behavior**
I ran the `example_glfw_opengl3` from the original ImGui C++ repository and it looks perfectly ok. I'd expect elements rendered using this crate to look the same size.

**Screenshots**

Taken from `imgui-rs` example `hello_world`

![2021-07-09_17-15](https://user-images.githubusercontent.com/6002855/125101015-08333c80-e0da-11eb-9824-c4c98819d9a1.png)

Taken from `imgui` (the C++ library) example `example_glfw_opengl3`

![2021-07-09_17-15_1](https://user-images.githubusercontent.com/6002855/125101029-0c5f5a00-e0da-11eb-9a5b-f66371032650.png)

**Please describe your environment**
 - The issue is reproducible on my laptop using imgui-rs version 0.7.0, commit `794ece895673a94fe480e1d81587108f34c8f586` which is what `master` points to at the time of writing
 - On the laptop I'm running Manjaro Linux with Plasma 5.21.4 on X11. `Linux elia-laptop-nix 5.10.34-1-MANJARO #1 SMP Sun May 2 11:29:56 UTC 2021 x86_64 GNU/Linux`
 - My laptop is a XPS 13 7390 2-in-1 with a 1920x1200 screen with 169 DPI
 - The desktop (on which the issue does not appear) has a 1920x1080 screen with 92 DPI

**Comment by dbr** [comment]
The winit platform handler tries to determine a reasonable scaling to make the UI a consistent size on high-DPI screens (I can't recall if the C++ examples do this or if they are fixed at 1.0x scaling?)

There is logged messages from `winit` (maybe only visible if you use something like `env_logger`) which output the scaling factor it decides on:
```
[winit::platform_impl::platform::x11::window][INFO] Guessed window scale factor: 1.25
```

This scaling is then applied on this line in the example code:

https://github.com/imgui-rs/imgui-rs/blob/794ece895673a94fe480e1d81587108f34c8f586/imgui-examples/examples/support/mod.rs#L49

I guess your 169DPI screen may have a scaling factor of `>1.5` which would mean the scaling factor gets rounded up to 2.0, since the example code uses `HiDpiMode::Rounded`. I'm not too sure this is the best option - it makes the built-in fixed-size font look nice and sharp, but in practice I found it makes UI's either overly small or, as you have seen, overly giant.

You can ignore all this cleverness and change that line to `HiDpiMode::Fixed(1.0)`, but I'd recommend `HiDpiMode::Default` (although it can involve a bit of care to get nice looking font rendering - one major thing being to tweak `font_size` to be rounded to nearest integer, and I also had to increase the font over-sampling font-config settings)

**Comment by dbr** [comment]
Oh actually there's already a PR to change the scaling to `HiDpiMode::Default` - #504 :partying_face:

**Comment by eliaperantoni** [comment]
@dbr The Hi-DPI mode was definitely my issue! Though I still get giant UI elements when using `HiDpiMode::Default`.

What works for me is `HiDpiMode::Locked(1.0)`. Maybe because I have no scaling (or rather, 1.0 scaling) on my desktop environment and I'm used to that?

I've checked on the `example_glfw_opengl3` from the original ImGui repository and GLFW actually detects that I have a scaling of 1.0 and uses that.

I think this issue is worth closing as it doesn't seem to be `imgui-rs`' fault but rather `winit`'s.
