### ISSUE TITLE
`slider` example is broken on macos

### ISSUE THREAD

**Issue by dymk** [imgui-rs/imgui-rs#565]
**Describe the bug**

When running the `slider` example, a crash is observed when selecting the "Example 1: Basic sliders" option. 

Here's a snippet of the stacktrace of the crash: https://gist.github.com/dymk/4a4dd569c2f035a8aebf7e2bb44c5bf8

The specific assertion failing is this:

```cpp
IM_ASSERT(*(const float*)p_min >= -FLT_MAX / 2.0f && *(const float*)p_max <= FLT_MAX / 2.0f);
```

The values of:
- `p_min`: `(const float) $0 = -3.40282347E+38`
- `p_max`: `(const float) $1 = 3.40282347E+38`
- `FLT_MAX` from `float.h`: `$2 = 3.40282347E+38`

In particular, the second clause of the above assertion is what's failing (cmp has been set to FLT_MAX):

```
p *(const float*)p_min >= -cmp / 2.0f
(bool) $8 = true
p *(const float*)p_max <= cmp / 2.0f
(bool) $9 = false
```

**To Reproduce**

Run slider example, select Basic sliders option

**Expected behavior**

It to not do that

**Screenshots**

**Please describe your environment**
 - imgui-rs version 0.8.0
 - macOS 11.3.1 (20E241)

**Other information**
Add related issues, suggestions about how to fix, any other context here.

**Comment by dbr** [comment]
Same crash occurs on Linux, and doesn't happen in 0.7

    slider: ./third-party/imgui-master/imgui/imgui_widgets.cpp:2974: bool ImGui::SliderBehavior(const ImRect&, ImGuiID, ImGuiDataType, void*, const void*, const void*, const char*, ImGuiSliderFlags, ImRect*): Assertion `*(const float*)p_min >= -3.40282346638528859811704183484516925e+38F / 2.0f && *(const float*)p_max <= 3.40282346638528859811704183484516925e+38F / 2.0f' failed.

Pretty sure this is caused by the change to remove the (slightly insane) default ranges from `imgui::Slider`,

https://github.com/imgui-rs/imgui-rs/commit/7b644bf159#diff-9a0a75de1c60eb3869ca58aa756e5d200ff93fa919ef3c302144810e18f2550f

The library change itself is good I think, just the example code needs fixed, as

    Slider::new(im_str!("f32 value")).build(ui, &mut state.f32_value);

was changed to

    Slider::new(im_str!("f32 value"), -f32::MIN, f32::MAX).build(ui, &mut state.f32_value);

..which isn't the same thing (should have been `-f32::MIN/2.0, f32::MAX/2.0`)

It's probably more sensible to show this usage with `u8::MAX`, and maybe a warning somewhere about the sliders being limited to `+/-f32/2`

I'll look at fixing this up tomorrow hopefully!

(this is a good motivation to try and finish up #482 so we can potentially run the examples in CI in a meaningful manner!)

**Comment by dbr** [comment]
Worked on in #568

**Comment by dbr** [comment]
Example now updated via #568!
