### ISSUE TITLE
Crash when pasting in text input fields

### ISSUE THREAD

**Issue by EmbersArc** [imgui-rs/imgui-rs#580]
**Describe the bug**
When pasting text with enough characters inside a text input field, the application crashes with a memory error.

**To Reproduce**
Run the `test_window_impl` example and paste text inside the `input_text` widget, potentially multiple times in a row until the application crashes.

**Expected behavior**
No crash.

**Please describe your environment**
 - imgui-rs version 0.8.0
 - Any OS

**Comment by dbr** [comment]
I think this is part of the same problem as #564

It's fixed in the latest `main` branch (I'm able to paste the entire of warandpeace.txt into the multi-line input in master several times, but crashes when pasting a few lines in 0.8)

However this should be covered by the fixes @sanbox-irl is going to backport as 0.8.1 when he has the time :partying_face:

**Comment by EmbersArc** [comment]
Yes, you're right. No issues on the `main` branch. Thanks!
