### ISSUE TITLE
imgui-rs 0.8.2 docs failing to build

### ISSUE THREAD

**Issue by zmoote** [imgui-rs/imgui-rs#594]
Hey there,

I was getting ready to read the docs for imgui 0.8.2 but noticed that the build was failing.

I looked at the build logs and it seems to be getting stuck on specifically imgui-sys 0.8.2, with a fatal error:
`fatal error: misc/freetype/imgui_freetype.h: No such file or directory`

Does imgui still use that header? Or perhaps the pathing is incorrect?

Anyways, hopefully, this helps solve the build. I may take a look through the repo and submit a pull request if I anticipate being able to fix it myself :)

**Comment by dbr** [comment]
The header is used when the `--features freetype` is enabled, and I'm pretty sure the problem comes from the `exclude` line in `imgui-sys/Cargo.toml`

```
exclude = ["third-party/*.json", "third-party/*.lua", "third-party/imgui/*/"]
```

The final glob pattern excludes everything in the `misc/` folder, which includes the now required `misc/freetype/*`

I initially thought this was related to the changes in #557 but, of course not, as those changes are for 0.9 onwards (not present in the 0.8.x branch) - but that branch likely has a variation of the same problem

**Comment by dbr** [comment]
(PR pending in #595)
