### ISSUE TITLE
Serialization of draw data

### ISSUE THREAD

**Issue by rmccrystal** [imgui-rs/imgui-rs#606]
Is there any way to serialize the draw list so you can run your rendering code in webasm, serialize it, and render your draw list outside of webasm?

**Comment by dbr** [comment]
There's no serialization support currently (e.g a `serde` feature), but everything relevant in the `DrawData` struct should be publically accessible

If you are using a custom renderer, then you could possibly just:

- Pull the data from the DrawList into a set of custom structs
- Serialize that
- Deserialize it to `MyCustomDrawList`, and use this data in your custom renderer

Since the public DrawData API is used for all the renderers, you should be able to access all required data quite easily. Tedious, but, would work with any current imgui-rs release.

It's more difficult if you want to deserialize to an actual `imgui::DrawData` object (to use an existing renderer). I think this would need changes to imgui itself, as there's no way to create an `DrawData` instance from an arbitrary source - would probably need something like a feature-gated `DrawList::from_serde` method (which would probably also have to be marked as `unsafe`, as the renderers probably expect all the data to be valid - e.g `total_idx_count` set to correct value, indexes all in range, etc)

**Comment by rmccrystal** [comment]
Ok so I tried what you said, added a layer for imgui::Context and imgui::DrawData that can be serialized containing the same api as that of imgui's, but now I'm getting an error from my modified imgui-glium-renderer saying it can't find the texture ID of 0. Any ideas?

**Comment by dbr** [comment]
Texture ID 0 is most probably the font atlas; simplest thing might be to generate any old font atlas on the client and see if everything else works (text might be blank or gabled if they don't exactly match, but everything else should work in theory)

**Comment by rmccrystal** [comment]
You're right, I was serializing the context which isn't bidirectional so the texture id of the font wasn't updating.

Here's the repo for the sterilization layer: https://github.com/rmccrystal/imgui-rs-serialize

**Comment by dbr** [comment]
Note in v0.11 there is a new `OwnedDrawData` added in #721 - doesn't directly solve the problem of serialization, but may help simplify this in some cases
