### ISSUE TITLE
doc.rs build is failing

### ISSUE THREAD

**Issue by Jasper-Bekkers** [imgui-rs/imgui-rs#631]
It looks like the build is failing because a C++ file is missing, probably not included in the Cargo.toml file to be uploaded or something?

https://docs.rs/crate/imgui/0.8.2/builds/482652

**Comment by dbr** [comment]
Yep the `freetype.cpp` was unintentionally excluded from the `.crate`, which caused builds to fail when a) using the crate and b) using freetype feature (whereas if you built from git it worked fine)

This should all be fixed in the `patch-0.8` branch (#629 and specifically 155e7584db6108dcc57e2822aeb346613c5b4bbb) - we just need to make a new 0.8.3 release to fix this - @sanbox-irl ?

**Comment by hammypants** [comment]
Currently the repo displays the latest main, wherein none of the examples match the API that you get from pulling 0.8.2, which _that_ documentation you can't even see (in the accustomed format) because the doc.rs build is failing. So, to learn how to use the current available imgui-rs, you have to swap the github repo (or pull) to 0.8.2 and browse it by hand.

Rather confusing.

**Comment by thomcc** [comment]
It looks like I still have publish privileges, so if @sanbox-irl is too busy I can cut a 0.8.3.

**Comment by thomcc** [comment]
Okay. I'll do it tomorrow, when I have a little more time. I'll also try to update the bundled imgui, do we have documentation for the process there? (I believe the docs I wrote a while ago on it have fallen out of date(

**Comment by thomcc** [comment]
It looks like updating imgui to 1.87 will be a breaking change, so I'll hold off on that til after.

**Comment by dbr** [comment]
Fixed a while ago with 0.9 release
