### ISSUE TITLE
Consider keeping a simpler version of the imgui-rs Api

### ISSUE THREAD

**Issue by coderedart** [imgui-rs/imgui-rs#633]
considering imgui-rs seems to be going towards a closure based api like egui, I wanted to point out in advance towards https://github.com/emilk/egui/issues/1004# .

having closure based api is a pain to write bindings for or expose the gui for scripting vms embedded in any game (or application). imgui-rs is built on the already simply C bindings which are unsafe, but it would be cool if there's a safer, but still not closure based api first and then building closure based functions on top of them. 

ofcourse, if it seems like this means too much work, ignore the request :) but it would be really helpful to people making games (engines) or such who want to expose a plugin api which allows faster iteration of features / gui design too.

rust game + imgui-rs + deno (v8) for scripting would be a great performant and extendable combo. 
(deno is going to release their "how to embed deno in rust app/game" blogpost soon by april)

ofcourse, the same could be said about Python or lua based on the user preference.

**Comment by dbr** [comment]
That's a very good point, the closure based API's are nice as they clearly structure the code (e.g "all the things in side this closure are inside this window"), but they do make things harder in some cases (FFI most definitely, but even simpler things like they can unintentionally move objects, or make `?` based error handling a bit tedious)

Is there cases were we have introduced closure-only part of the API? If so that was probably a mistake - I don't think the intent is ever to have closures be the only approach; we should always provide an alternative (most commonly using "drop tokens").

For example for creating windows, we allow both:

```rust
ui.window("Title").build(|| { ui.text("...") });
```
and
```rust
if let Some(_window) = ui.window("Title").begin() {
    ui.text("...");
}
```

Since the `.build(...)` method is basically a thin wrapper around the `.begin()` method it's not much extra work to have both

**Comment by coderedart** [comment]
Ah, maybe I misunderstood. I saw the 0.9 tracking issue about incoming breaking changes, and i assumed that you will eventually be removing the previous api to have only a single closure based one.

just wanted to bring this point up anyway before its too late, so that the bindings use-case is considered.

**Comment by coderedart** [comment]
just another follow up, but how ffi safe is imgui-rs? is it possible to pass the context across ffi boundary for dynamic libs to use it?

**Comment by dbr** [comment]
> I saw the 0.9 tracking issue about incoming breaking changes, and i assumed that you will eventually be removing the previous api to have only a single closure based one.

Ah I see! No the breaking changes are more around how the window objects etc are initially created - the parts where they are used should be reasonably consistent - meaning methods like `.build(|| ui.text())` should continue to coexist with `.begin()` for the foreseeable future I think

> just another follow up, but how ffi safe is imgui-rs?

I'm not 100% sure, @thomcc or @sanbox-irl would be able to answer more authoritatively, but, as far as I understand, it should be safely doable with a bit of care. At least `imgui-rs` shouldn't introduce any further limiations beyond imgui itself (e.g the `Context` or `Ui` objects aren't threadsafe, but neither is imgui itself)
