### ISSUE TITLE
imgui-examples appear 'glitchy' on Windows

### ISSUE THREAD

**Issue by cirrusone** [imgui-rs/imgui-rs#642]
Hello,

Using the examples from folder `imgui-examples` from the main repo on Windows 10, most of them are appearing 'glitchy' for me (see below image).  I have tried toggling with_vsync(true) / with_vsync(false) in `../support/mod.rs` without success.

Does this mean I need to use an alternative renderer or should I be looking elsewhere to resolve this?

![2022-05-11-16-06-54](https://user-images.githubusercontent.com/10389314/167884898-c3ade97a-8584-4cc6-bfd4-f6632846502e.gif)

**Comment by dbr** [comment]
That is pretty strange! I would suspect it might be a graphics driver related issue rather than the renderer, but not sure

There was a note in the 1.86 release notes about glitching, https://github.com/ocornut/imgui/releases/tag/v1.86 although it mentions it was limited to modal windows and the keyboard-nav overlay (whereas the attached video is just stuff in standard windows)

A few ideas of other things to test, to narrow it down to "bug with imgui-rs" or something else:

- The upstream imgui examples (i.e from https://github.com/ocornut/imgui ), as they are more widely used than the Rust bindings
- Trying the `imgui-glow-renderer` example (we use the latest `main` version of this renderer on linux+windows without issue)
- Same example but from the `v0.8` releases (as they are definitely tested on Windows)

**Comment by cirrusone** [comment]
I think you're correct, it does look like a specific issue with my PC (4790K iGPU only) or drivers. I have tested the following

- `imgui-examples` are working fine with no glitching on another Windows 10 PC
- `imgui-glow-renderer` works fine on problematic PC with no issues.
- Dear imgui C++ demo works fine on problematic PC with no issues.

I'll use the `imgui-glow-renderer` for now. Thank you.
