### ISSUE TITLE
Some questions regarding imgui-rs

### ISSUE THREAD

**Issue by Raj2032** [imgui-rs/imgui-rs#650]
Hi I have some questions regarding imgui-rs:
1. Is there a renderer that I can use which supports mobile and desktop operating systems?
2. Does it have caching capabilities?
3. Is it more customizable compared to [egui](https://github.com/emilk/egui)?

**Comment by sanbox-irl** [comment]
1. Sure -- your best options are either `glow`, `wgpu`, or using a software renderer. that's in your court though -- imgui isn't a renderer. this repository contains some helpful guys though for each of those.
2. yep, but not user controlled. if you don't touch a menu, it doesn't remake the verts. But imgui is an immediate mode gui.
3. I don't know egui enough to comment. in terms of looks, I ~think~ imgui has the edge stuff, but i'm not positive at all

**Comment by dbr** [comment]
> your best options are either glow, wgpu, or using a software renderer

`winit` [supports iOS](https://github.com/rust-windowing/winit/blob/v0.26.1/src/platform/ios.rs) and [Android](https://github.com/rust-windowing/winit/blob/v0.26.1/src/platform/android.rs).

For the renderer side of things - wgpu supports iOS and Android, and there is [a imgui-rs renderer here](https://github.com/Yatekii/imgui-wgpu-rs).

imgui-rs has a supported `imgui-glow-renderer` - glow [supports android](https://github.com/grovesNL/glow/blob/d88346cd9e93603d68c574c981bbdc3c8d76045a/.github/workflows/ci.yml#L62), and I *assume* it probably works on iOS but weirdly there isn't a single mention of "iOS"/"iphone"/"apple" on the glow project's issue tracker (which is slightly surprising! Might just mean it works so smoothly no one has ever had an issue :shrug:)

> Is it more customizable compared to [egui](https://github.com/emilk/egui)?

In terms of visual customizablity, I'd say they are both "quite similar" - they both let you tweak a lot of things in their respective style. There will certainly be slight differences between the two, but it's not a "one is macOS where you will fight to change the colour of a button"-level of differences.

However as sanbox says, imgui appears to have a edge currently - e.g a few obvious differences playing around with the egui demo:
- Geometry of sliders are more tweakable in dear imgui - you can change the rounding on the grab handle between a sphere and a vertical line, whereas egui seems "stuck" as a bordered-circle
- More specific widgets can be customized globally by the style config (e.g you can tweak the hovered colour for scrollbar or slider or button separately, whereas in egui it's appears to apply only to "all hovered widgets")

With all that said, the immediate-mode approach of both libraries make it quite easy to create fully custom widets from drawing primitives, so with enough effort you can likely make things look however you want (more easily than in something like Qt)

Personally I would decide between the two based on:

1. Long term development stability. Dear ImGui has been pretty consistently developed since 2015, and is relied on and funded by some quite large companies. egui is a relatively new project by comparison (initial release was in May 2020)
2. Ease of use with wasm - egui not having any C++ code behind it means compiling for web-browser via WASM is pretty simple. This is possible with imgui-rs but will require more work
3. Availibilty of example code - again mostly a function of being around for longer, but dear imgui's issue tracker is full of examples of how to do weird random esoteric things which are invaluable when required. Similarly there's lots of example widgets and so on. The examples might be in C++ but are generally directly translatable into imgui-rs (or any other bindings)

Your specific project will change the relevance of these points these a lot, as will the passage of time!

**Comment by Raj2032** [comment]
@sanbox-irl @dbr Hey guys thanks for your response :)

Just some more quesitons:

1. Is it possible to have these kinds of buttons?

![image](https://user-images.githubusercontent.com/29293830/179756980-4574fd70-8625-4e8a-a8c5-a727f040e34e.png)

?

2.:
> yep, but not user controlled. if you don't touch a menu, it doesn't remake the verts. But imgui is an immediate mode gui.

In regards to this, lets say I have a few objects, if I touch one object, would it re-draw all the objects?

**Comment by dbr** [comment]
> Is it possible to have these kinds of buttons?

Definitely - best way is probably to use the "invisible button" as the base (it lets you handle clicking and checking hover-state by `ui.is_item_active()` etc), then you draw the background shape via the `DrawListMut` API (similar to [this example](https://github.com/imgui-rs/imgui-rs/blob/v0.8.2/imgui-examples/examples/draw_list.rs)), and then draw the icon image on top [like this example](https://github.com/imgui-rs/imgui-rs/blob/v0.8.2/imgui-examples/examples/custom_textures.rs#L99-L121) (the way is demonstrates loading images is pretty overly verbose; you really don't need to define one struct per image)

> In regards to this, lets say I have a few objects, if I touch one object, would it re-draw all the objects?

Yep but the idea is that drawing is fast enough that redrawing everything is perfectly fine

Somewhat tangental but extrapolating [from this](https://github.com/ocornut/imgui/wiki/About-the-IMGUI-paradigm), in theory there's no reason an imgui library couldn't do selective redraw similar to how React.js works (it's "just" much more complex to implement)

**Comment by Raj2032** [comment]
@dbr Thanks for your response.

> Somewhat tangental but extrapolating [from this](https://github.com/ocornut/imgui/wiki/About-the-IMGUI-paradigm), in theory there's no reason an imgui library couldn't do selective redraw similar

So like selective redraw is very similar to retained graphics?

**Comment by thomcc** [comment]
> So like selective redraw is very similar to retained graphics?

No, you could do either in either, but immediate mode tends to be used in scenarios where you're going to redraw the whole world anyway with a GPU api, so there'd be very little benefit of implementing selective redraw.
