### ISSUE TITLE
Crash with set_keyboard_focus_here() and move window

### ISSUE THREAD

**Issue by tetenpapier** [imgui-rs/imgui-rs#652]
**Describe the bug**
When I have a window with a text widget and force focus with `set_keyboard_focus_here`, it crashed sometimes when I move the window (of the widget).

**To Reproduce**
Here a snipet of the code that can reproduce the bug. Try to move the window which contains the input Test.

```rust
let mut tmp = String::new();
ui.set_keyboard_focus_here();
ui.input_text("Test", &mut tmp).build();
```

You'll got this error in the terminal:
```
./third-party/imgui-docking/imgui/imgui.cpp:16442: void ImGui::BeginDockableDragDropSource(ImGuiWindow*): Assertion `g.ActiveId == window->MoveId' failed.
```

**Expected behavior**
No crash and can move window. The text should be focus when we don't drag the window.

**Please describe your environment**
 - imgui-rs version : last commit on master with docking and tables-api features
 - Arch Linux x86_64, Kernel 5.18.10
 - rustc 1.64.0-nightly (7b46aa594 2022-07-05)

**Other information**
I think it's related with [this issue](https://github.com/ocornut/imgui/issues/4836) but I found nothing more.

I've also tried a check to avoid the focus but it's not working : 
```rust
if !ui.is_mouse_dragging(imgui::MouseButton::Left) && ui.is_window_focused() {
    ui.set_keyboard_focus_here();
}
```

**Comment by dbr** [comment]
Surprising crash, but I guess it's uncommon to call `set_keyboard_focus_here` every frame like that (it would more often be called something like `if ui.button("...") { ui.set_keyboard_focus_here(); }`)

This appears to be an upstream bug with ~v1.86 - with imgui at rev 15b4a064f9244c430e65214f7249b615fb394321 (from around 22 Dec 2021) as I get the same crash in C++ doing this:

```
void my_display_code()
{
    {
        static float f = 0.0f;

        ImGui::Begin("Hello, world!");

	ImGui::SetKeyboardFocusHere();
        ImGui::SliderFloat("float", &f, 0.0f, 1.0f);

        ImGui::End();
    }
}
```

It seems to be fixed in latest imgui (at least in current master branch at cb8ead1f7198924f97e52973d115e1d4eaeda2f3 from 12 July 2022)

So I think this will be solved via #609

**Comment by tetenpapier** [comment]
Thank you ! I'll leave this issue open so people with the same problem will get an answer

**Comment by dbr** [comment]
Should be fixed in `main` branch, which will be the upcoming v0.10
