### ISSUE TITLE
Default to WGPU renderer?

### ISSUE THREAD

**Issue by nu11ptr** [imgui-rs/imgui-rs#667]
**Is your feature request related to a problem? Please describe.**

The default supported renderers seem to be based on OpenGL. While today most major platforms support OpenGL, it is already deprecated on [macOS](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_intro/opengl_intro.html). It could conceivably be removed in the future breaking applications.

**Describe the solution you'd like**

Automatically choosing the best (aka native) renderer on the target platform (although keeping a manual override seems mandatory given the target audience is often game engines). While this is not my area of expertise, I would expect that to be OpenGL (or Vulkan?) on Linux/Unix, Metal on macOS, and DirectX on Windows. It is my understanding that WGPU is an abstraction over these APIs (only OpenGL ES though, not sure if that limits things). Thinking it might make sense to target WGPU by default for this reason?

**Describe alternatives you've considered**

Using the WGPU standalone renderer, but it isn't clear if it is always up to date with the main project. Also, the example looked convoluted and large. Not sure if this is due to how it works or was just a large example.

**Additional context**

I am very new to this project and IM GUis in general and just starting to play around. Therefore, it is possible this request doesn't make sense in the context/architecture of this project. Further, I have very little (read: none) experience with the aforementioned APIs or projects. My sole goal is simply to ensure any future projects I write on imgui-rs stay running for years without breakage.

**Comment by dbr** [comment]
This is an interesting topic, and something I spent quite a while considering last year when I started a large project which heavily uses imgui

It's hard to give a concerete answer to this without a huge amount of text which is full of caveats, so in (hopefully not too many) bullet point form:

1. There isn't really a default renderer for imgui-rs (or Dear ImGui) as such - there's just the one we happen to use for the `imgui-examples`. That is to say, `imgui-wgpu-renderer` wouldn't gain any technical advantage from being "the default"
2. wgpu is under quite active development
3. Knowing if `imgui-wgpu` is up to date with imgui-rs is relatively simple - if it depends on the latest release, then, yep! Can be checked on https://crates.io/crates/imgui-wgpu/0.20.0/dependencies (current release of imgui-rs is 0.8, and it depends on that)
4. wgpu currently has a faster iteration cycle than us - so in this case it's arguably benifical to have imgui-wgpu be separate project from `imgui-rs`, so it can be updated for new wgpu releases independantly (otherside of the argument is we should be doing more regular imgui-rs, but that's a different topic!)

Regarding "any future projects I write on imgui-rs stay running for years without breakage", this is a tricky problem with, I suspect, no perfect solution currently!

1. As mentioned, wgpu is being quite actively designed and developed - so even if you used wgpu now, in 5 years time wgpu will likely look quite different (compared to the same code using, say, OpenGL via glow). By this I only mean wgpu isn't a "implement and forget" solution, because the underlying API's are also in flux
2. For us, our main targets were Windows+Linux for the foreseeable future, with support for macOS being less important - so, currently, targeting OpenGL was pretty straight forward choice for us. OpenGL might be deprecated there, but it will most likely keep working for a while (by which time wgpu will hopefully solidify into the unambigious defacto choice :crossed_fingers: )
4. With an application UI which is pretty much "pure Dear ImGui", it was quite easy to switch imgui-rs renderer (e.g we changed from glium to glow with minimal drama - most of the work was just reimplementing the texture API methods). Obviously if you do lots of custom OpenGL stuff


> Using the WGPU standalone renderer

I would say there's not enough benefit at this point to merge imgui-wgpu-rs and imgui-rs (and if the people behind the former would be interested!), which is what would be requried for this.

However in the near-future when Apple more actively moves to deleting support for OpenGL, I would increase the priority of this. Apple have some history of deprecating things for a long time (e.g the Carbon framework was deprecated in either 2007 or 2012, but it was quite widely depended on, and was only "fully killed off" in macOS 10.15 Catalina in 2019)

## Summary

Not sure if this all answers your question or just rasies more, but in summary I'd say: the examples should remain on glow for now, and maybe re-evaluate this some time next (e.g if wgpu gets a "1.0"-ish release, that would change my opinion greatly!)
