### ISSUE TITLE
Code from mod.rs doesn't compile

### ISSUE THREAD

**Issue by Smurfy98** [imgui-rs/imgui-rs#668]
I tried copying the code from [mod.rs](https://github.com/imgui-rs/imgui-rs/blob/main/imgui-examples/examples/support/mod.rs) , but when I compile I get the following error:

```
error[E0308]: mismatched types
  --> src\support.rs:52:48
   |
52 |         platform.attach_window(imgui.io_mut(), window, dpi_mode);
   |                                                ^^^^^^ expected struct `winit::window::Window`, found struct `glium::glutin::window::Window`
   |
   = note: expected reference `&winit::window::Window`
              found reference `&glium::glutin::window::Window`
   = note: perhaps two different versions of crate `winit` are being used?
```

I left everything basically as is, except for removing the whole `  imgui.fonts().add_font(&[ ....` part.

My `Cargo.toml` looks as follows:
```
[package]
name = "spherical"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
winit = "0.27.2"
glium = "0.32.1"
imgui-glium-renderer = "0.8.2"
imgui-winit-support = "0.8.2"
imgui = "0.8.2"
```

I read #637 but I am not sure about versions etc as this was a few months ago. I think there should finally be a complete working example available and it should be clarified, which versions of winit / glium are compatible with the current imgui-rs "release".

**Comment by dbr** [comment]
Sorry for the slow reply!

I think you just need to do `glium = "0.30"` because the latest release of imgui-rs (0.8) ises this, as seen here:
https://crates.io/crates/imgui-glium-renderer/0.8.2/dependencies

You may also need to use winit 0.25 (instead of 0.27 mentioned in your Cargo.toml)

It's a bit tedious to wrangle the versions - the easiest way I've found to debug this is to use `cargo tree` - for example,

```
$ cat Cargo.toml 
[package]
name = "spherical"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
winit = "0.27.2"
glium = "0.32.1"
imgui-glium-renderer = "0.8.2"
imgui-winit-support = "0.8.2"
imgui = "0.8.2"

$ cargo tree
spherical v0.1.0 (/tmp/spherical)
├── glium v0.32.1
...
├── imgui v0.8.2
...
├── imgui-glium-renderer v0.8.2
│   ├── glium v0.30.2
...
│   └── imgui v0.8.2 (*)
├── imgui-winit-support v0.8.2
│   ├── imgui v0.8.2 (*)
│   └── winit v0.25.0
...
├── log v0.4.17 (*)
└── winit v0.27.3 (*)
```

Here the top-level glium dependency version is `glium v0.32.1` but the one we need to use is under `imgui-glium-renderer` which is `glium v0.30.2`

The solution is to either
1. update to newer `imgui-glium-renderer` (currently, not possible because 0.8 is newer), therefore..
2. Specify your top-level glium to be 0.30

Hope that makes sense!

Once done #664 should help this, as it'd give a nice up-to-date/copy-pastable set of versions to use

**Comment by sanbox-irl** [comment]
Going to close this as it's stale
