### ISSUE TITLE
 Get rid of background window

### ISSUE THREAD

**Issue by Stuntlover-TM** [imgui-rs/imgui-rs#669]
I've just started playing around with imgui-rs and the first thing I notice is that there's a window which has the actual GUI in it, how do I get rid of or make that invisible?

**Comment by dbr** [comment]
Sorry for the slow repsonse!

This is sort of just "how dear imgui works" - unlike GTK or Cocoa etc, imgui-rs is traditionally used to create debug interfaces within a game (which is just a large canvas, and imgui draws into this) - this is explained much better in the upstream imgui repo (rather than here in the Rust bindings), https://github.com/ocornut/imgui

That said, you can make reasonable looking standalone applications - simplest workaround is just to make your main imgui window occupy the full (OS) window, basically something like:

```rust
let flags =
    // No borders/title etc
    imgui::WindowFlags::NO_DECORATION | imgui::WindowFlags::NO_MOVE
    // Don't raise window on focus (as it'll hide floating windows)
    | imgui::WindowFlags::NO_BRING_TO_FRONT_ON_FOCUS | imgui::WindowFlags::NO_NAV_FOCUS
;

ui.window("Main")
    .position([0.0, 0.0], imgui::Condition::Always)
    .size(ui.io().display_size, imgui::Condition::Always)
```

With the next (0.9) release, you will easily be able to enable the 'docking' feature which makes this much more useful

In future, a much better solution is being developed upstream via the docking and viewports feature,

https://github.com/ocornut/imgui/issues/1542
..which is being integrated into the Rust bindings here
https://github.com/imgui-rs/imgui-rs/pull/619

..which will basically mean each the imgui windows can becomes it's own floating OS window
