### ISSUE TITLE
Support SDL_Renderer for rendering

### ISSUE THREAD

**Issue by DragonSWDev** [imgui-rs/imgui-rs#670]
**Is your feature request related to a problem? Please describe.**
Dear ImGUI has support for SDL_Renderer as renderer that let's use Dear ImGUI with SDL2 without any additional rendering libraries. SDL_Renderer can be hardware accelerated but can also work without it with software rendering. In some places it can be useful thing to have. If I'm not mistaken imgui-rs supports SDL2 as platform but doesn't support SDL_Renderer.

**Describe the solution you'd like**
Add support for SDL_Renderer.

**Describe alternatives you've considered**
Software accelerated OpenGL, DirectX and other APIs can be considered as alternative but compared to SDL_Renderer you still needs to basically write your own renderer while you don't have to do it with SDL_Renderer as it provides pretty clean and easy to use API for copying bitmaps from place to place, handles low level stuff etc. 

**Additional context**
Dear ImGUI support for SDL_Renderer started as third party project called imgui_sdl. It's part of Dear ImGUI starting from version 1.85. Old project is still archived on GitHub so maybe it can be useful for making Rust version.

**Comment by dbr** [comment]
Having a renderer with a software backend would be useful - I started writing a very simple one intended for automated documentation in https://github.com/imgui-rs/imgui-rs/pull/482 - but if there's a fully robust oen in SDL that might solve two problems with one

However if someone wants to write this renderer, it is likely best keeping it as a separate project - otherwise it adds more maintenance to the imgui-rs project (which we are already struggling to make time for!)

The goal with the stuff in this repo is basically to have two implementations (two renderers + two platform-support libraries), to ensure we avoid doing anything specific to one. We unfortunately can't support every possible platform (there's just too many possible options and combinations)

**Comment by DragonSWDev** [comment]
Sounds good to me, thank you for explanation.
