### ISSUE TITLE
Make io related enums to support serde Serialize/Deserialize 

### ISSUE THREAD

**Issue by ruby3141** [imgui-rs/imgui-rs#769]
### Is your feature request related to a problem? Please describe.

Because `imgui::Key` does not support `serde`, this kind of thing is not possible.

```rs
use serde::{Deserialize, Serialize};
use imgui::Key;

#[derive(Serialize, Deserialize)]
pub struct HoykeyConfig {
    some_hotkey: Key,
    // ...
}
```

Providing proxy enum to use `#[serde(remote="...")]` is kind of viable, but not recommendable since `imgui::Key` has 140 entries.

### Describe the solution you'd like

Make io related enums of this crate to derive `serde::{Serialize, Deserialize}`.

**Comment by sanbox-irl** [comment]
We've been historically avoiding adding serde directly because we don't really have control over these types -- fundamentally they could change in a way that breaks serde compatibility.

How do you feel about making a proxy type (ie, `Foo: From<imgui::Key>`)?

**Comment by ruby3141** [comment]
I already did, with huge chunk of copy-pasted enum definition.
It is working, but I'm still wonder if there's other way to achieve it without copy-paste.

**Comment by sanbox-irl** [comment]
Since Rust promises the pattern-patching will always be exhaustive, I do think that your approach is actually future proofed. Annoying, yes, but future proofed.

I do the same thing with the imgui style settings for the same reason as above. For what it's worth, the reasoning that "because imgui controls this type means we can't serde it" is weak imo. If there's sufficient interest in trying, I'd probably try!

**Comment by sanbox-irl** [comment]
Going to close this as I think this isn't a direction we're going to go

**Comment by ruby3141** [comment]
I think you should close this as "not planned", not "completed".
Thank you for considering my request. Keep up the good work.

**Comment by sanbox-irl** [comment]
@ruby3141 good point, and thank you! Sorry we ended up not going that way!
