### ISSUE TITLE
Make properties of window, frame etc 

### ISSUE THREAD

**Issue by mruegenberg** [imgui-rs/imgui-rs#92]
Hello,
if there is a way to access properties of e.g a window such as its size, I was unable to find how to do that.
This would be useful e.g for making an UI that reacts to the window being resized.

A possible API might be to integrate this into the existing builder pattern: 

~~~~
    let mut size = (0.0,0.0);
    ui.window(im_str!("Hello world"))
        .size((900.0, 500.0), ImGuiCond::FirstUseEver)
        .get_size(&size).
        .build(|| {
            // ...
        });
~~~~

Or the window might be passed to its inner function (which might be weird with the way the API currently works, but might be made ok by passing an immutable object (see also #90):
~~~~
    let mut size = (0.0,0.0);
    ui.window(im_str!("Hello world"))
        .size((900.0, 500.0), ImGuiCond::FirstUseEver)
        .build(|it: &Ui::Window| {
            // ...
            let zesize = it.get_size();
        });
~~~~

**Comment by Gekkio** [comment]
I don't think there's a way to do what you want but it's a good idea! But first, I think we need to split properties into two groups: defined properties and calculated properties.

Defined properties IMHO don't need to be accessible through the API, because they are always passed by the library user and therefore the user already has all the values. For example:

```rust
let use_borders = true;
ui.window(im_str!("Hello world"))
    .show_borders(use_borders)
    .build(|w| {
      w.has_borders(); // <- no point in having this, because use_borders is already easily accessible
    });
``` 

Calculated properties such as size are a different story. For example, window position and size could be accessible using some API using the style in your second example. Remember that the position and size passed to the builder are not necessarily the real values that the window ends up having.

It's also not just properties...there's some "window APIs" in imgui that are currently not exposed at all in the imgui crate but could be added. For example:

```rust
ui.window(im_str!("Hello world"))
    .build(|w| {
        if w.is_appearing() {
            w.focus();
            println!("Content region width: {}", w.content_region_width());
        }
    });
```

**Comment by mruegenberg** [comment]
Hey, can't say much about this except that I think you're right on all points :)

**Comment by dbr** [comment]
Closing old ticket

Not sure what the state of the lbirary was at the time, but the initial problem (getting window size) is doable now via
```rust
ui.window("Hello world")
    .size((900.0, 500.0), FirstUseEver)
    .build(|| {
        // ...
        let zesize = ui.window_size();
    });
```

Would be nicer if that method was through some more explicit "Window" object passed in, but.. that would be a somewhat drastic change, and the current approach is basically direct mapping of the C++ API which is also nice
